**Import libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Load dataset**

In [2]:
df = pd.read_csv("Retail_Business_Performance_Dataset.csv")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Rows: 12000
Columns: 18

,Order_ID,Order_Date,Customer_ID,Region,State,Category,Sub_Category,Product,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Inventory_Days,Payment_Method,Sales_Channel,Season
0,ORD-000649,2024-01-01,CUST-01946,West,Gujarat,Furniture,Tables,Work Table 4,6,229.17,0.00,1375.02,1120.16,254.86,34,Net Banking,Online,Winter
1,ORD-000756,2024-01-01,CUST-01215,South,Karnataka,Office Supplies,Binders,Binder 15,1,31.06,0.15,26.40,21.37,5.03,14,Net Banking,Marketplace,Winter
2,ORD-000980,2024-01-01,CUST-02166,East,Jharkhand,Home & Kitchen,Storage,Storage Unit 4,2,120.27,0.00,240.54,158.38,82.16,26,Credit Card,Store,Winter
3,ORD-001138,2024-01-01,CUST-01384,North,Delhi,Home & Kitchen,Cookware,Cookware Set 1,4,118.96,0.00,475.84,330.25,145.59,49,UPI,Online,Winter
4,ORD-001978,2024-01-01,CUST-00733,South,Andhra Pradesh,Home & Kitchen,Storage,Storage Unit 9,10,117.23,0.10,1055.07,819.32,235.75,53,Debit Card,Store,Winter

**Check data types**

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        12000 non-null  object
 1   Order_Date      12000 non-null  object
 2   Customer_ID     12000 non-null  object
 3   Region          12000 non-null  object
 4   State           12000 non-null  object
 5   Category        12000 non-null  object
 6   Sub_Category    12000 non-null  object
 7   Product         12000 non-null  object
 8   Quantity        12000 non-null  int64
 9   Unit_Price      12000 non-null  float64
 10  Discount        12000 non-null  float64
 11  Sales           12000 non-null  float64
 12  Cost            12000 non-null  float64
 13  Profit          12000 non-null  float64
 14  Inventory_Days  12000 non-null  int64
 15  Payment_Method  12000 non-null  object
 16  Sales_Channel   12000 non-null  object
 17  Season          12000 non-null  object
dtypes: float64(5), int64(2), object(11)
memory usage: 1.6+ MB

**Check missing values**

In [4]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Region            0
State             0
Category          0
Sub_Category      0
Product           0
Quantity          0
Unit_Price        0
Discount          0
Sales             0
Cost              0
Profit            0
Inventory_Days    0
Payment_Method    0
Sales_Channel     0
Season            0
dtype: int64

**Check duplicates**

In [5]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

**Convert date**

In [6]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

**Check duplicate Order IDs**

In [7]:
print("Duplicate Order IDs:", df['Order_ID'].duplicated().sum())

Duplicate Order IDs: 0

**Check numerical columns**

In [8]:
numeric_columns = [
    'Quantity',
    'Unit_Price',
    'Discount',
    'Sales',
    'Cost',
    'Profit',
    'Inventory_Days'
]

df[numeric_columns].describe()

,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Inventory_Days
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,3.012750,158.043019,0.086842,430.813508,346.273089,84.540418,39.293833
std,2.061215,130.945666,0.071413,522.081582,441.554329,90.392023,25.013789
min,1.000000,22.770000,0.000000,17.900000,12.020000,-30.860000,2.000000
25%,1.000000,46.660000,0.050000,105.285000,76.347500,26.810000,22.000000
50%,2.000000,117.220000,0.100000,233.420000,175.495000,52.450000,33.000000
75%,4.000000,244.882500,0.150000,543.647500,431.225000,110.100000,49.000000
max,10.000000,495.950000,0.250000,4919.000000,4288.360000,879.740000,120.000000

## **Create important analytical columns**

**Profit Margin**

In [9]:
df['Profit_Margin'] = (df['Profit'] / df['Sales']) * 100

**Revenue before discount**

In [10]:
df['Gross_Sales'] = df['Quantity'] * df['Unit_Price']

**Discount Amount**

In [11]:
df['Discount_Amount'] = df['Gross_Sales'] - df['Sales']

**Year**

In [12]:
df['Year'] = df['Order_Date'].dt.year

**Month**

In [13]:
df['Month'] = df['Order_Date'].dt.month

**Month Name**

In [14]:
df['Month_Name'] = df['Order_Date'].dt.month_name()

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         12000 non-null  object
 1   Order_Date       12000 non-null  datetime64[ns]
 2   Customer_ID      12000 non-null  object
 3   Region           12000 non-null  object
 4   State            12000 non-null  object
 5   Category         12000 non-null  object
 6   Sub_Category     12000 non-null  object
 7   Product          12000 non-null  object
 8   Quantity         12000 non-null  int64
 9   Unit_Price       12000 non-null  float64
 10  Discount         12000 non-null  float64
 11  Sales            12000 non-null  float64
 12  Cost             12000 non-null  float64
 13  Profit           12000 non-null  float64
 14  Inventory_Days   12000 non-null  int64
 15  Payment_Method   12000 non-null  object
 16  Sales_Channel    12000 non-null  object
 17  Season           12000 non-null  object
 18  Profit_Margin    12000 non-null  float64
 19  Gross_Sales      12000 non-null  float64
 20  Discount_Amount  12000 non-null  float64
 21  Year             12000 non-null  int32
 22  Month            12000 non-null  int32
 23  Month_Name       12000 non-null  object
dtypes: datetime64[ns](1), float64(8), int32(2), int64(2), object(11)
memory usage: 2.1+ MB

**Save the cleaned dataset**

In [17]:
output_file = "Retail_Business_Performance_Cleaned.csv"

df.to_csv(
    output_file,
    index=False
)

print(
    f"Cleaned dataset saved as: {output_file}"
)

Cleaned dataset saved as: Retail_Business_Performance_Cleaned.csv